name: hephaestus

# Template for hephaestus services
x-hephaestus-template: &hephaestus-template
  restart: unless-stopped
  image: hephaestus-dev:latest
  build:
    dockerfile: docker/Dockerfile.dev
    pull: false
    context: ..
    args:
      BASE_IMAGE: gcr.io/sunflower-container-registry/hephaestus-hephaestus-base:latest
  depends_on:
    hephaestus-base:
      condition: service_completed_successfully
  command: tail -F /dev/null
  ports: []
  cap_add:
    - SYS_PTRACE
    - NET_ADMIN
  shm_size: 512
  security_opt:
    - seccomp:unconfined
  environment:
    DISPLAY: ${DISPLAY:-}
    SCCACHE_SERVER_PORT: 4228
    HEPHAESTUS_PATH: /workspaces/hephaestus
  # devices:
  #   - /dev/dri:/dev/dri
  working_dir: /workspaces/hephaestus
  volumes:
      - /dev:/dev
      - ${HOME}/.config/nvim:/workspaces/.config/nvim
      - ${HOME}/.local:/workspaces/.local
      - ${HOME}/.ssh:/workspaces/.ssh
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../:/workspaces/hephaestus
      # - shellhistory:/dc/shellhistory
      # - vscode-server:/workspaces/.vscode-server
      - cache:/workspaces/.cache

services:
  hephaestus-base:
    build:
      dockerfile: Dockerfile
      pull: false
      context: .
      tags:
        - hephaestus-base:${DOCKER_TAG:-latest}
        - ghcr.io/olympus-robotics/hephaestus:${DOCKER_TAG:-latest}
      args:
        BASE_IMAGE: ubuntu:22.04
    command: 'echo "build is completed"'

  hephaestus-pub:
    <<: *hephaestus-template
    deploy:
      mode: replicated
      replicas: 1
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub

  hephaestus-sub:
    <<: *hephaestus-template
    deploy:
      mode: replicated
      replicas: 5
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_sub

  # hephaestus-bag:
  #   <<: *hephaestus-template
  #   command: /workspaces/hephaestus/bazel-bin/modules/bag/bag_recorder --output_bag /tmp/this_is_a_bag.mcap

  hephaestus-bridge:
    <<: *hephaestus-template
    container_name: hephaestus-bridge
    command: /workspaces/hephaestus/bazel-bin/modules/websocket_bridge/app -c /workspaces/hephaestus/modules/websocket_bridge/config/ws_bridge-config.yaml
    ports:
      - "4228:4228"  # sccache server
      - "8765:8765"  # websocket bridge
      - "8080:8080"  # hephaestus web interface
      - "3000:3000"  # hephaestus web interface (alternative port)

volumes:
  cache:
