name: hephaestus

# Template for hephaestus services
x-hephaestus-template: &hephaestus-template
  restart: unless-stopped
  image: hephaestus-dev:latest
  build:
    dockerfile: docker/Dockerfile.dev
    pull: false
    context: ..
    args:
      BASE_IMAGE: gcr.io/sunflower-container-registry/hephaestus-hephaestus-base:latest
  depends_on:
    hephaestus-base:
      condition: service_completed_successfully
  command: tail -F /dev/null
  ports: []
  cap_add:
    - SYS_PTRACE
    - NET_ADMIN
  shm_size: 512
  security_opt:
    - seccomp:unconfined
  environment:
    DISPLAY: ${DISPLAY:-}
    SCCACHE_SERVER_PORT: 4228
    HEPHAESTUS_PATH: /workspaces/hephaestus
  # devices:
  #   - /dev/dri:/dev/dri
  working_dir: /workspaces/hephaestus
  volumes:
      - /dev:/dev
      - ${HOME}/.config/nvim:/workspaces/.config/nvim
      - ${HOME}/.local:/workspaces/.local
      - ${HOME}/.ssh:/workspaces/.ssh
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../:/workspaces/hephaestus
      # - shellhistory:/dc/shellhistory
      # - vscode-server:/workspaces/.vscode-server
      - cache:/workspaces/.cache

services:
  hephaestus-base:
    build:
      dockerfile: Dockerfile
      pull: false
      context: .
      tags:
        - hephaestus-base:${DOCKER_TAG:-latest}
        - ghcr.io/olympus-robotics/hephaestus:${DOCKER_TAG:-latest}
      args:
        BASE_IMAGE: ubuntu:22.04
    command: 'echo "build is completed"'

  helper:
    <<: *hephaestus-template
    container_name: hephaestus-helper
    command: tail -F /dev/null

  # hephaestus-pub:
  #   <<: *hephaestus-template
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #   command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub

  # hephaestus-sub:
  #   <<: *hephaestus-template
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #   command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_sub


  # Start 40 instances of the zenoh_pub_sub example
  # Each instance will have a unique node-id from 1 to 40
  # This is useful for testing the pub-sub system with multiple nodes
  # Each node will publish and subscribe to topics with unique IDs
  hephaestus-pub-sub-0:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 0

  hephaestus-pub-sub-1:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 1

  hephaestus-pub-sub-2:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 2

  hephaestus-pub-sub-3:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 3

  hephaestus-pub-sub-4:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 4

  hephaestus-pub-sub-5:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 5

  hephaestus-pub-sub-6:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 6

  hephaestus-pub-sub-7:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 7

  hephaestus-pub-sub-8:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 8

  hephaestus-pub-sub-9:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 9

  hephaestus-pub-sub-10:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 10

  hephaestus-pub-sub-11:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 11

  hephaestus-pub-sub-12:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 12

  hephaestus-pub-sub-13:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 13

  hephaestus-pub-sub-14:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 14

  hephaestus-pub-sub-15:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 15

  hephaestus-pub-sub-16:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 16

  hephaestus-pub-sub-17:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 17

  hephaestus-pub-sub-18:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 18

  hephaestus-pub-sub-19:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 19

  hephaestus-pub-sub-20:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 20

  hephaestus-pub-sub-21:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 21

  hephaestus-pub-sub-22:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 22

  hephaestus-pub-sub-23:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 23

  hephaestus-pub-sub-24:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 24

  hephaestus-pub-sub-25:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 25

  hephaestus-pub-sub-26:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 26

  hephaestus-pub-sub-27:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 27

  hephaestus-pub-sub-28:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 28

  hephaestus-pub-sub-29:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 29
  hephaestus-pub-sub-30:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 30

  hephaestus-pub-sub-31:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 31

  hephaestus-pub-sub-32:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 32

  hephaestus-pub-sub-33:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 33

  hephaestus-pub-sub-34:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 34

  hephaestus-pub-sub-35:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 35

  hephaestus-pub-sub-36:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 36

  hephaestus-pub-sub-37:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 37

  hephaestus-pub-sub-38:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 38

  hephaestus-pub-sub-39:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 39

  hephaestus-pub-sub-40:
    <<: *hephaestus-template
    command: /workspaces/hephaestus/bazel-bin/modules/examples/zenoh_pub_sub --num-topics ${NUM_TOPICS} --high-rate ${HIGH_RATE} --medium-rate ${MEDIUM_RATE} --num-nodes ${NUM_NODES} --array-size ${ARRAY_SIZE} --node-id 40

  # hephaestus-bag:
  #   <<: *hephaestus-template
  #   command: /workspaces/hephaestus/bazel-bin/modules/bag/bag_recorder --output_bag /tmp/this_is_a_bag.mcap

  hephaestus-bridge:
    <<: *hephaestus-template
    container_name: hephaestus-bridge
    command: /workspaces/hephaestus/bazel-bin/modules/websocket_bridge/app -c /workspaces/hephaestus/modules/websocket_bridge/config/ws_bridge-config.yaml
    ports:
      - "4228:4228"  # sccache server
      - "8765:8765"  # websocket bridge
      - "8080:8080"  # hephaestus web interface
      - "3000:3000"  # hephaestus web interface (alternative port)
    logging:
      driver: "none"

volumes:
  cache:
